CREATE TABLE IF NOT EXISTS stations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    x_coord REAL NOT NULL,
    y_coord REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS lines (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    color TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS player_profile (
    id INTEGER PRIMARY KEY CHECK(id = 1),
    username TEXT NOT NULL DEFAULT 'Player',
    total_playtime_seconds INTEGER NOT NULL DEFAULT 0
);
